// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Ability struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type CreatePokemonInput struct {
	Name        string   `json:"name"`
	Description string   `json:"description"`
	Category    string   `json:"category"`
	Type        []string `json:"type"`
	Abilities   []string `json:"abilities"`
}

type Mutation struct {
}

type Pokemon struct {
	ID          string         `json:"id"`
	Name        string         `json:"name"`
	Description string         `json:"description"`
	Category    string         `json:"category"`
	Type        []*PokemonType `json:"type"`
	Abilities   []*Ability     `json:"abilities"`
}

type PokemonType struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type Query struct {
}

type UpdatePokemonInput struct {
	Name        *string  `json:"name,omitempty"`
	Description *string  `json:"description,omitempty"`
	Category    *string  `json:"category,omitempty"`
	Type        []string `json:"type,omitempty"`
	Abilities   []string `json:"abilities,omitempty"`
}
